* tips
** view valid date from pem file
   #+BEGIN_SRC sh
     % openssl x509 -startdate -enddate -noout -in apns.pem
     notBefore=Sep 20 01:01:06 2016 GMT
     notAfter=Oct 20 01:01:06 2017 GMT
   #+END_SRC
   [[http://stackoverflow.com/a/21297927/514411][bash - How to determine SSL cert expiration date from a PEM encoded certificate? - Stack Overflow]]
** dns server
   dnsmasq. use alias from /etc/hosts
** monitoring
   monit. monitoring service and send mail or restart ,...
*** monit
**** refs
***** [[https://www.unixmen.com/install-and-configure-monit-on-centos-rhel-ubuntu-debian/][Install and Configure Monit on CentOS/RHEL/Ubuntu/Debian | Unixmen]]
***** [[https://www.howtoforge.com/tutorial/server-monitoring-with-munin-and-monit-on-centos/2/][Server monitoring with Munin and Monit on CentOS 7.2 - Page 2 - Page 2]]
***** [[http://qiita.com/ksworks/items/0f3bbfa9e0ba49b5ef06][CentOS 6.5にmonitをインストールしてプロセス監視をする - Qiita]]
***** [[http://shanon-tech.blogspot.jp/2011/11/15monit.html][15分で始めるmonitによるサーバ監視 - SHANON　Engineer's　Blog]]
**** logs
***** install
     #+BEGIN_SRC sh
       $ sudo yum install monit
       $ vi /etc/monit.conf
       ...
       set httpd port 2812 and
       #     use address localhost  # only accept connection from localhost
           use address 192.168.0.X  # only accept connection from localhost
       #     allow localhost        # allow localhost to connect to the server and
           allow admin:monit      # require user 'admin' with password 'monit'
           allow @monit           # allow users of group 'monit' to connect (rw)
           allow @users readonly  # allow users of group 'users' to connect readonly
       ...
       $ sudo /sbin/service monit start
       Starting monit: monit: generated unique Monit id aaaaaaabbbbbbbbbbcccccc and stored to '/var/monit/id'
       Starting monit daemon with http interface at [192.168.0.X:2812]
                                                                  [  OK  ]
       $ sudo /sbin/chkconfig --list monit
       monit           0:off   1:off   2:on    3:on    4:on    5:on    6:off
     #+END_SRC
***** access to http://192.168.0.X:2812
***** add conf for wifi connection
****** /etc/monit.d/monitrc
       #+BEGIN_SRC sh
         $ cat /etc/monit.d/monitrc
         set logfile syslog facility log_daemon
         check program pgm with path "/path/to/test-wifi.sh" with timeout 1000 seconds
           start program = "/path/to/connect-wifi.sh"
           if status != 0 then restart
           if 5 restarts within 5 cycles then timeout
      #+END_SRC
****** test-wifi.sh
       #+BEGIN_SRC sh
         $ cat /path/to/test-wifi.sh
         #!/bin/bash
         curl -m 1 -I http://192.168.0.X
         exit $?
      #+END_SRC
****** connect-wifi.sh
       #+BEGIN_SRC sh
         $ cat /path/to/connect-wifi.sh
         #!/bin/bash
         wlan=wlan0
         SSID=SOME_SSID
         /sbin/iwconfig $wlan essid $SSID
         curl -X POST -d 'payload={"text":"wifi reconnected"}' https://chat-webhook/hashhashhash
      #+END_SRC
****** test and restart monit
       #+BEGIN_SRC sh
         $ sudo monit -t
         Control file syntax OK
         $ sudo /sbin/service monit restart
         Stopping monit:                                            [  OK  ]
         Starting monit: Starting monit daemon with http interface at [192.168.0.X:2812]
                                                                    [  OK  ]
       #+END_SRC
*** hubot
*** mail
*** connect wi-fi by command
    [[http://raspberrypi.stackexchange.com/a/5121][wireless - How to automatically reconnect WiFi? - Raspberry Pi Stack Exchange]]
    #+BEGIN_SRC sh
      wlan=wlan0
      SSID=SOME_SSID
      sudo /sbin/iwconfig $wlan essid $SSID
    #+END_SRC
** line notify
   https://notify-bot.line.me/my/
   #+BEGIN_SRC sh
     curl -X POST -H 'Authorization: Bearer tooookeeeeen' -d 'message=Hello World!' https://notify-api.line.me/api/notify
   #+END_SRC
   (if you use =-F= option instead of =-d= option, message will garbled with some environment (like in edison))
** mathjax
   - [[http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference][MathJax basic tutorial and quick reference - Mathematics Meta Stack Exchange]]
** router
   - [[http://yabe.jp/gadgets/edgerouter-x/][EdgeRouter X がすごい | yabe.jp]]
** remove empty directories
   [[http://unix.stackexchange.com/a/46326][linux - how can I recursively delete empty directories in my home directory? - Unix & Linux Stack Exchange]]
   This command removes only 1 layer. If directory has empty directories, it should exec again and again.
   #+BEGIN_SRC sh
     find ./target -type d -empty -delete
     find ./target -type d -empty -print
   #+END_SRC
** install/uninstall bash on windows
   lxrun /uninstall /full
   lxrun /install
   [[http://www.howtogeek.com/261188/how-to-uninstall-or-reinstall-windows-10s-ubuntu-bash-shell/][How to Uninstall (or Reinstall) Windows 10’s Ubuntu Bash Shell]]
** find modified in 24h
   find /directory_path -mtime -1 -ls
   [[http://stackoverflow.com/a/16086041/514411][linux - Scripts: find the files have been changed in last 24 hours - Stack Overflow]]
** diff epub
   gem install epdiff
   epdiff old.epub new.epub
   [[http://qiita.com/takahashim/items/dad97795213e9e570f30][EPUBファイルの差分を取る - Qiita]]
** htaccess http <--> https redirect
   [[http://d.hatena.ne.jp/mrgoofy33/20100914/1284414817][.htaccessでHTTPアクセスをSSLでリダイレクト(逆もアリ) - hogehoge foobar Blog Style5]]
   #+BEGIN_SRC conf
     # HTTPSページ用.htaccess
     <IfModule mod_rewrite.c>
         RewriteEngine on
         RewriteCond %{HTTPS} off
         RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
     </IfModule>
     # HTTPページ用.htaccess

     <IfModule mod_rewrite.c>
         RewriteEngine on
         RewriteCond %{HTTPS} on
         RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [R,L]
     </IfModule>
   #+END_SRC

   - [L]は、定義の最終行（Last）を意味します。この行以降のRewriteRuleは無視されます。一番最後の行に書きます。
   - [L]を書かなくても動作します。
   - [R]は、リダイレクトを行います。
   - http://memorva.jp/memo/linux/mod_rewrite.php
** concat pdf
   #+BEGIN_SRC sh
    /System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py --output output.pdf --verbose infile1.pdf infile2.pdf
   #+END_SRC
   [[http://pastebin.com/xvhkZMU3][AppleScript merge PDFs in OS X - Pastebin.com]]
** GitHub contributions calendar
   https://github.com/users/peccu/contributions
   (this svg should be added `xmlns="http://www.w3.org/2000/svg"` to svg tag)
   [[./contributions.svg]]
** CSS tips
   [[http://qiita.com/_upto_me_/items/8f00ce8548a5cefd3d93][知っておくと役に立つCSS - Qiita]]
** delete docket images
   [[http://qiita.com/tora470/items/cd577526ec87a8a53797][Dockerお掃除コマンド - Qiita]]
   - 動いていないコンテナを消す
   docker ps -aq -f status=exited -f status=dead | xargs docker rm
   - コンテナのステータスはこちら
   created
   restarting
   running
   paused
   exited
   dead
   - タグの付いてないイメージを消す
   docker images -f "dangling=true" -q | xargs docker rmi
** list up yum installed files
   [[http://stackoverflow.com/a/1766413/514411][linux - Determining the path that a yum package installed to - Stack Overflow]]
   =rpm -ql packagename=
** can't yum update
   comment =mirrorlist=, uncomment =baseurl= in =/etc/yum.repos.d/CentOS-Base.repo=
** screencast (mov) to gif
   [[https://gist.github.com/dergachev/4627207][OS X Screencast to animated GIF]]
   #+BEGIN_SRC sh
     ffmpeg -i in.mov -s 1006x530 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > out.gif
   #+END_SRC

   [[http://stackoverflow.com/a/11236144/514411][How can I get the resolution (width and height) for a video file from a linux command line? - Stack Overflow]]
   #+BEGIN_SRC sh
     ffprobe -v quiet -print_format json -show_streams mew-yasnippet.mov|jq '.streams[0].width'
     ffprobe -v quiet -print_format json -show_streams mew-yasnippet.mov|jq '.streams[0].height'
   #+END_SRC
   Then,
   #+BEGIN_SRC sh
     function mov2gif(){
         if [ -z $1 ] ; then
             echo usage: $0 file
             return
         fi
         INFILE=$1
         OUTFILE=${INFILE%.*}.gif
         WIDTH=$(ffprobe -v quiet -print_format json -show_streams mew-yasnippet.mov|jq '.streams[0].width')
         HEIGHT=$(ffprobe -v quiet -print_format json -show_streams mew-yasnippet.mov|jq '.streams[0].height')
         ffmpeg -i $INFILE -s ${WIDTH}x$HEIGHT -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > $OUTFILE
     }
   #+END_SRC
** ls date format
   [[https://unix.stackexchange.com/a/275730][date - Set ls -l time format - Unix & Linux Stack Exchange]]
   #+BEGIN_SRC sh
     ls -l --time-style=long-iso
   #+END_SRC
** check port
   [[https://apple.stackexchange.com/a/117648][terminal - How can I list my open network ports with netstat? - Ask Different]]
   - netstat -tup tcp
   - lsof -i :4444
   - sudo lsof -PiTCP -sTCP:LISTEN
** get weekday
   [[https://stackoverflow.com/a/46024878/514411][bash - How can we get weekday based on given date in unix - Stack Overflow]]
   #+BEGIN_SRC shell-script
     $ date -j -f '%m-%d-%Y' "09-01-2017" +'%A'
     Friday
     $ date -j -f '%m-%d-%Y' "09-01-2017" +'%a'
     Fri
   #+END_SRC
** exec command each lines from pipe
   [[https://stackoverflow.com/a/2711008/514411][bash - How to apply shell command to each line of a command output? - Stack Overflow]]
   #+BEGIN_SRC sh
     cat $1 | while read line
     do
       echo $line | somecommand
     done
   #+END_SRC
** split file by size
   [[https://stackoverflow.com/a/2016918/514411][bash - How to split a large text file into smaller files with equal number of lines? - Stack Overflow]]
   =split -l 20000 -a 3 somefile somefile.=

   =-a= means suffix length
** create basic auth header
   [[https://stackoverflow.com/questions/3044315/how-to-set-the-authorization-header-using-curl#comment69464812_36979985][oauth - How to set the authorization header using curl - Stack Overflow]]
   #+BEGIN_SRC sh
     # usage `basic user:password`
     # => -H "Authorization: Basic dXNlcjpwYXNzd29yZA=="
     function basic(){
       echo -H \"Authorization: Basic $(echo -ne $1 | base64)\"
     }
   #+END_SRC
