* tips
** view valid date from pem file
   #+BEGIN_SRC sh
     % openssl x509 -startdate -enddate -noout -in apns.pem
     notBefore=Sep 20 01:01:06 2016 GMT
     notAfter=Oct 20 01:01:06 2017 GMT
   #+END_SRC
   [[http://stackoverflow.com/a/21297927/514411][bash - How to determine SSL cert expiration date from a PEM encoded certificate? - Stack Overflow]]
** dns server
   dnsmasq. use alias from /etc/hosts
** monitoring
   monit. monitoring service and send mail or restart ,...
*** monit
**** refs
***** [[https://www.unixmen.com/install-and-configure-monit-on-centos-rhel-ubuntu-debian/][Install and Configure Monit on CentOS/RHEL/Ubuntu/Debian | Unixmen]]
***** [[https://www.howtoforge.com/tutorial/server-monitoring-with-munin-and-monit-on-centos/2/][Server monitoring with Munin and Monit on CentOS 7.2 - Page 2 - Page 2]]
***** [[http://qiita.com/ksworks/items/0f3bbfa9e0ba49b5ef06][CentOS 6.5にmonitをインストールしてプロセス監視をする - Qiita]]
***** [[http://shanon-tech.blogspot.jp/2011/11/15monit.html][15分で始めるmonitによるサーバ監視 - SHANON　Engineer's　Blog]]
**** logs
***** install
     #+BEGIN_SRC sh
       $ sudo yum install monit
       $ vi /etc/monit.conf
       ...
       set httpd port 2812 and
       #     use address localhost  # only accept connection from localhost
           use address 192.168.0.X  # only accept connection from localhost
       #     allow localhost        # allow localhost to connect to the server and
           allow admin:monit      # require user 'admin' with password 'monit'
           allow @monit           # allow users of group 'monit' to connect (rw)
           allow @users readonly  # allow users of group 'users' to connect readonly
       ...
       $ sudo /sbin/service monit start
       Starting monit: monit: generated unique Monit id aaaaaaabbbbbbbbbbcccccc and stored to '/var/monit/id'
       Starting monit daemon with http interface at [192.168.0.X:2812]
                                                                  [  OK  ]
       $ sudo /sbin/chkconfig --list monit
       monit           0:off   1:off   2:on    3:on    4:on    5:on    6:off
     #+END_SRC
***** access to http://192.168.0.X:2812
***** add conf for wifi connection
****** /etc/monit.d/monitrc
       #+BEGIN_SRC sh
         $ cat /etc/monit.d/monitrc
         set logfile syslog facility log_daemon
         check program pgm with path "/path/to/test-wifi.sh" with timeout 1000 seconds
           start program = "/path/to/connect-wifi.sh"
           if status != 0 then restart
           if 5 restarts within 5 cycles then timeout
      #+END_SRC
****** test-wifi.sh
       #+BEGIN_SRC sh
         $ cat /path/to/test-wifi.sh
         #!/bin/bash
         curl -m 1 -I http://192.168.0.X
         exit $?
      #+END_SRC
****** connect-wifi.sh
       #+BEGIN_SRC sh
         $ cat /path/to/connect-wifi.sh
         #!/bin/bash
         wlan=wlan0
         SSID=SOME_SSID
         /sbin/iwconfig $wlan essid $SSID
         curl -X POST -d 'payload={"text":"wifi reconnected"}' https://chat-webhook/hashhashhash
      #+END_SRC
****** test and restart monit
       #+BEGIN_SRC sh
         $ sudo monit -t
         Control file syntax OK
         $ sudo /sbin/service monit restart
         Stopping monit:                                            [  OK  ]
         Starting monit: Starting monit daemon with http interface at [192.168.0.X:2812]
                                                                    [  OK  ]
       #+END_SRC
*** hubot
*** mail
*** connect wi-fi by command
    [[http://raspberrypi.stackexchange.com/a/5121][wireless - How to automatically reconnect WiFi? - Raspberry Pi Stack Exchange]]
    #+BEGIN_SRC sh
      wlan=wlan0
      SSID=SOME_SSID
      sudo /sbin/iwconfig $wlan essid $SSID
    #+END_SRC
** line notify
   https://notify-bot.line.me/my/
   #+BEGIN_SRC sh
     curl -X POST -H 'Authorization: Bearer tooookeeeeen' -d 'message=Hello World!' https://notify-api.line.me/api/notify
   #+END_SRC
   (if you use =-F= option instead of =-d= option, message will garbled with some environment (like in edison))
** mathjax
   - [[http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference][MathJax basic tutorial and quick reference - Mathematics Meta Stack Exchange]]
** router
   - [[http://yabe.jp/gadgets/edgerouter-x/][EdgeRouter X がすごい | yabe.jp]]
** remove empty directories
   [[http://unix.stackexchange.com/a/46326][linux - how can I recursively delete empty directories in my home directory? - Unix & Linux Stack Exchange]]
   This command removes only 1 layer. If directory has empty directories, it should exec again and again.
   #+BEGIN_SRC sh
     find ./target -type d -empty -delete
     find ./target -type d -empty -print
   #+END_SRC
** install/uninstall bash on windows
   lxrun /uninstall /full
   lxrun /install
   [[http://www.howtogeek.com/261188/how-to-uninstall-or-reinstall-windows-10s-ubuntu-bash-shell/][How to Uninstall (or Reinstall) Windows 10’s Ubuntu Bash Shell]]
** find modified in 24h
   find /directory_path -mtime -1 -ls
   [[http://stackoverflow.com/a/16086041/514411][linux - Scripts: find the files have been changed in last 24 hours - Stack Overflow]]
** diff epub
   gem install epdiff
   epdiff old.epub new.epub
   [[http://qiita.com/takahashim/items/dad97795213e9e570f30][EPUBファイルの差分を取る - Qiita]]
** htaccess http <--> https redirect
   [[http://d.hatena.ne.jp/mrgoofy33/20100914/1284414817][.htaccessでHTTPアクセスをSSLでリダイレクト(逆もアリ) - hogehoge foobar Blog Style5]]
   #+BEGIN_SRC conf
     # HTTPSページ用.htaccess
     <IfModule mod_rewrite.c>
         RewriteEngine on
         RewriteCond %{HTTPS} off
         RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
     </IfModule>
     # HTTPページ用.htaccess

     <IfModule mod_rewrite.c>
         RewriteEngine on
         RewriteCond %{HTTPS} on
         RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [R,L]
     </IfModule>
   #+END_SRC

   - [L]は、定義の最終行（Last）を意味します。この行以降のRewriteRuleは無視されます。一番最後の行に書きます。
   - [L]を書かなくても動作します。
   - [R]は、リダイレクトを行います。
   - http://memorva.jp/memo/linux/mod_rewrite.php
** concat pdf
   #+BEGIN_SRC sh
    /System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py --output output.pdf --verbose infile1.pdf infile2.pdf
   #+END_SRC
   [[http://pastebin.com/xvhkZMU3][AppleScript merge PDFs in OS X - Pastebin.com]]
** GitHub contributions calendar
   https://github.com/users/peccu/contributions
   (this svg should be added `xmlns="http://www.w3.org/2000/svg"` to svg tag)
   [[./contributions.svg]]
** CSS tips
   [[http://qiita.com/_upto_me_/items/8f00ce8548a5cefd3d93][知っておくと役に立つCSS - Qiita]]
